DSPRJT-5997: Actualización en la página web de nuevos perfiles de cifras regionalizados
datasketch/sib-colombia pull request #10
Opened 2024-02-28 14:19 UTC by Angela2201

2024-02-28 14:37 UTC, ddazal requested changes

2024-02-28 14:37 UTC, ddazal commented on components/MapDepartmentObservations.jsx
> +  const values = [max, 2500, 2000, 1500, 1000, 500, min]
¿Puede haber ocasiones en las que `max` sea menor a 2500 o en las que `min` sea mayor a 500? Si sí, entonces debes buscar otra estrategia para hacer la leyenda.

2024-02-28 14:37 UTC, ddazal commented on components/MapDepartmentSpecies.jsx
> +  const values = [max, 2500, 2000, 1500, 1000, 500, min]
El mismo comentario que dejé en components/MapDepartmentObservations.jsx

2024-03-14 14:35 UTC, ddazal commented on components/headers/HeadRegion.jsx
> +      <div className={classNames('bg-cover bg-center pt-8 lg:pt-14 pb-3.5 h-[550px] ')} style={{ backgroundImage: 'url("/images/banner-principales/santander.jpg")' }}>
Aquí siempre va a mostrar la imagen banner de santander. No sé si es un requerimiento, pero dejo el comentario para que revises.

2024-03-14 14:40 UTC, ddazal commented on components/WaffleChart.jsx
> +    const waffle = d3.select('#waffle')
¡Muy bien!

Ahora revisa si puedes utilizar un ref para que el componente sea verdaderamente re-utilizable. Así como está, si llegases a utilizar este componente dos veces en la misma página tendrías dos `figure` con el id `waffle`. Se supone que los ids no deberían repetirse. Intenta algo por la línea de:

```jsx
const figureRef = useRef(null)

useEffect(() => {
    if (!figureRef.current) return

    const waffle = d3.select(figureRef.current)
    /* ... */
}, [figureRef])

return (<figure ref={figureRef}></figureRef>)
```

2024-03-14 14:41 UTC, ddazal commented on components/Slides.jsx
> +              </figure>
Acá tienes dos elementos figure con el mismo id. El primero viene de WaffleChart y el otro el que está en el jsx

2024-03-14 14:46 UTC, ddazal commented on components/MapDepartmentObservations.jsx
> +  }
Este código se repite en otro archivo. Busca la forma de refactorizarlo. Podría ser en un custom hook.

2024-04-03 19:48 UTC, Angela2201 commented on components/headers/HeadRegion.jsx
> +      <div className={classNames('bg-cover bg-center pt-8 lg:pt-14 pb-3.5 h-[550px] ')} style={{ backgroundImage: 'url("/images/banner-principales/santander.jpg")' }}>
Si, de acuerdo a varias reuniones con ellos, tomaron la decisión de dejar de fondo para todos los perfiles la imagen del banner de Santander.

2024-04-03 20:49 UTC, Angela2201 commented on components/Slides.jsx
> +              </figure>
Estaba probando y se me pasó borrarlo, porque ya lo había hecho en el componente WaffleChart

2024-04-11 15:01 UTC, ddazal approved these changes

2024-05-29 13:56 UTC, LuisFCalderon commented on components/BarPercent.jsx
> +  const capitalizeWords = (str) => {
Ya hay una funcion en /lib/funtions que hace esto, revisa si es lo que buscas y puedes usarla en dado caso

2024-05-29 13:57 UTC, LuisFCalderon commented on components/CardContentTem.jsx
> +  }
usar funcion capitalize de /lib/functions

2024-05-29 14:15 UTC, LuisFCalderon commented on hooks/useLegend.js
> +      }
Esto  lo puedes hacer con un ternario y algo commo esto quedaria mejor
` return length === 1 ? 1 : Math.pow(10, length - 1) `

2024-05-29 14:17 UTC, LuisFCalderon commented on hooks/useLegend.js
> +    let rounded
Tambien puedes usar el ternario aqui

2024-05-29 22:01 UTC, LuisFCalderon approved these changes

2024-05-29 22:03 UTC, merged